name: マイグレーション

on:
  push:
    branches:
      - main

jobs:
  apply-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies & tooling
        run: 
          npm install -g pnpm
          pnpm install
      - name: Apply migrations
        run: pnpm drizzle:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}